{% set name = "mache" %}
{% set version = "1.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mache/archive/refs/tags/{{ version }}.tar.gz
  sha256: b4208d79707c34d7b765083fac9cdfa851da026d5b9444743d58269a5d58e551

build:
  number: 0
  noarch: python
  entry_points:
    - mache = mache.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=60
  run:
    - python >={{ python_min }}
    - importlib_resources
    - jinja2
    - lxml
    - pyyaml
    - progressbar2
    - rsync

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - mache
  commands:
    - pip check
    - mache sync diags --help

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://docs.e3sm.org/mache/
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - altheaden
    - xylar
