{% set name = "mache" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mache/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8a11da8fa01820b216b33fc9c7d721604bf36d56bd61cc4866c893d2a7e3d327

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=60
  run:
    - python >={{ python_min }}
    - importlib_resources
    - jinja2
    - lxml
    - packaging
    - pyyaml
    - requests
    - rsync
    - termcolor
    - tqdm

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - mache
  commands:
    - pip check
    - mache sync diags --help

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://docs.e3sm.org/mache/
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - andrewdnolan
    - xylar
